export { default as HomeLayout } from "./HomeLayout";
export { default as Register } from "./Register";
export { default as Login } from "./Login";
export { default as Error } from "./Error";
export { default as DashboardLayout } from "./DashboardLayout";
export { default as Landing } from "./Landing";
export { default as  AllQuestions} from "./AllQuestions";
export { default as  AddQuestion} from "./AddQuestion";
export { default as  Profile} from "./Profile";
export { default as  Stats} from "./Stats";
export { default as  Admin} from "./Admin";
export { default as  Solve} from "./Solve";